config/routes.rb
Rails.application.routes.draw do

  resources :formas
  resources :contas
  resources :categorias

  resources :registros do
    post :duplicate, on: :member
  end
  resources :transferencias, controller: 'registros/transferencias'

  get 'financeiro/diario'
  get 'financeiro/anual'

  root 'financeiro#diario'

end

app/models/forma.rb
class Forma < ActiveRecord::Base
  belongs_to :conta
end

app/controllers/formas_controller.rb
# coding: UTF-8
class FormasController < ApplicationController
  before_action :set_forma, only: [:show, :edit, :update, :destroy]

  def index
    @formas = Forma.order(:nome)
  end

  def show
  end

  def new
    @forma = Forma.new
  end

  def edit
  end

  def create
    @forma = Forma.new(forma_params)

    if @forma.save
      redirect_to formas_path, notice: 'Forma criado com sucesso.'
    else
      render action: 'new'
    end
  end

  def update
    if @forma.update(forma_params)
      redirect_to formas_path, notice: 'Forma atualizada com sucesso.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @forma.destroy
    redirect_to formas_path, notice: 'Forma apagada com sucesso.'
  end

  private
    def set_forma
      @forma = Forma.find(params[:id])
    end

    def forma_params
      params.require(:forma).permit(:nome, :conta_id)
    end
end

app/helpers/formas_helper.rb
module FormasHelper
end

app/views/formas/_form.html.erb
<%= simple_form_for(@forma) do |f| %>

  <div class="row">
    <div class="col-md-6">
      <%= f.input :nome, label: 'Nome' %>
    </div>
    <div class="col-sm-6">
      <%= f.association :conta, label: 'Conta Preferncial', collection: Conta.all, label_method: :nome %>
    </div>
  </div>

  <div class="bottom-actions">
    <%= f.button :submit, 'Salvar Forma', class: 'btn btn-primary' %>

    <%= link_to icon(:trash, 'Apagar este Forma'),
                  @forma,
                  method: :delete,
                  data: { confirm: 'Tem certeza?' },
                  class: 'btn btn-sm text-danger pull-right' unless @forma.new_record? %>
  </div>
<% end %>

app/views/formas/edit.html.erb
<%= page_header "Editar Forma de Pagamento" do %>

  <%= link_to icon(:chevron_left, "Voltar"), formas_path, class: 'btn' %>

<% end %>

<%= render 'form' %>

app/views/formas/index.html.erb
<%= page_header "Formas de Pagamento" %>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Conta Preferencial</th>
    </tr>
  </thead>
  <tbody>
    <% @formas.each do |forma| %>
      <tr>
        <td><%= link_to forma.nome, edit_forma_path(forma) %></td>
        <td>
          <%= forma.conta.try :nome %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p class="index_count"><span><%= @formas.count %></span> formas encontradas.</p>

<div class="bottom-actions">
  <%= link_to(icon(:plus, 'Incluir Forma de Pagamento'), new_forma_path, class: 'btn btn-sm btn-primary') %>
</div>

app/views/formas/new.html.erb
<%= page_header "Nova Forma de Pagamento" do %>
  <%= link_to icon(:chevron_left, "Voltar"), formas_path, class: 'btn' %>
<% end %>

<%= render 'form' %>

app/views/formas/show.html.erb
<%= page_header "Exibir Forma" do %>
  <%= link_to icon(:chevron_left, "Voltar"), formas_path, class: 'btn' %>
  <%= link_to icon(:edit, 'Editar Forma'), edit_forma_path(@forma), class: 'btn btn-sm btn-primary' %>
<% end %>

<div class="panel panel-default">
  <div class="panel-body">

    <h4 class="text-primary">
      <%= @forma.nome %>
    </h4>

    <div class="row">

      <div class="col-md-4 col-sm-6">

        <dl class="dl-horizontal form">

          <dt>Nome</dt>
          <dd><%= @forma.nome %></dd>

        </dl>

      </div>

    </div>

  </div>
</div>