config/routes.rb
Rails.application.routes.draw do

  resources :formas
  resources :contas
  resources :categorias

  resources :registros do
    post :duplicate, on: :member
  end
  resources :transferencias, controller: 'registros/transferencias'

  get 'financeiro/diario'
  get 'financeiro/anual'

  root 'financeiro#diario'

end

app/models/conta.rb
class Conta < ActiveRecord::Base

  validates_length_of :nome, maximum: 20

  has_many :registros, -> { order(:data) }

  def Conta.to_select
    @@combo ||= Conta.update_select
  end

  def Conta.update_select
    @@combo = Conta.all.map {|c| [c.nome, c.id]}
  end

  def saldo
    registros.creditos.pagos.sum(:valor) - registros.debitos.pagos.sum(:valor)
  end

end

app/controllers/contas_controller.rb
# coding: UTF-8
class ContasController < ApplicationController
  before_action :set_conta, only: [:show, :edit, :update, :destroy]

  def index
    @search = Conta.search(params[:q])
    @contas = @search.result.order(:nome)
  end

  def show
  end

  def new
    @conta = Conta.new
  end

  def edit
  end

  def create
    @conta = Conta.new(conta_params)

    if @conta.save
      redirect_to contas_path, notice: 'Conta criada com sucesso.'
    else
      render action: 'new'
    end
  end

  def update
    if @conta.update(conta_params)
      redirect_to contas_path, notice: 'Conta atualizada com sucesso.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @conta.destroy
    redirect_to contas_path, notice: 'Conta apagada com sucesso.'
  end

  private
    def set_conta
      @conta = Conta.find(params[:id])
    end

    def conta_params
      params.require(:conta).permit(:nome)
    end
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/views/contas/_form.html.erb
<%= simple_form_for(@conta) do |f| %>

  <div class="row">
    <div class="col-md-6">

      <%= f.input :nome, label: 'Nome' %>
    </div>
  </div>

  <div class="bottom-actions">
    <%= f.button :submit, 'Salvar Conta', class: 'btn btn-primary' %>

    <%= link_to icon(:trash, 'Apagar este Conta'),
                  @conta,
                  method: :delete,
                  data: { confirm: 'Tem certeza?' },
                  class: 'btn btn-sm text-danger pull-right' unless @conta.new_record? %>
  </div>
<% end %>

app/views/contas/edit.html.erb
<%= page_header "Editar Conta" do %>

  <%= link_to icon(:chevron_left, "Voltar"), contas_path, class: 'btn' %>

<% end %>

<%= render 'form' %>

app/views/contas/index.html.erb
<%= page_header "Contas" %>


    <table class="table table-hover table-striped">
      <thead>
        <tr>
          <th>Nome</th>
        </tr>
      </thead>
      <tbody>
        <% @contas.each do |conta| %>
          <tr>
            <td><%= link_to conta.nome, edit_conta_path(conta) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <p class="index_count"><span><%= @contas.count %></span> contas encontradas.</p>

    <%= link_to(icon(:plus, 'Nova Conta'), new_conta_path, class: 'btn btn-primary') %>

app/views/contas/new.html.erb
<%= page_header "Novo Conta" do %>
  <%= link_to icon(:chevron_left, "Voltar"), contas_path, class: 'btn' %>
<% end %>

<%= render 'form' %>

app/views/contas/show.html.erb
<%= page_header "Exibir Conta" do %>
  <%= link_to icon(:chevron_left, "Voltar"), contas_path, class: 'btn' %>
  <%= link_to icon(:edit, 'Editar Conta'), edit_conta_path(@conta), class: 'btn btn-sm btn-primary' %>
<% end %>

<div class="panel panel-default">
  <div class="panel-body">

    <h4 class="text-primary">
      <%= @conta.nome %>
    </h4>

    <div class="row">

      <div class="col-md-4 col-sm-6">

        <dl class="dl-horizontal form">

          <dt>Nome</dt>
          <dd><%= @conta.nome %></dd>

        </dl>

      </div>

    </div>

  </div>
</div>