config/routes.rb
Rails.application.routes.draw do

  resources :formas
  resources :contas
  resources :categorias

  resources :registros do
    post :duplicate, on: :member
  end
  resources :transferencias, controller: 'registros/transferencias'

  get 'financeiro/diario'
  get 'financeiro/anual'

  root 'financeiro#diario'

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base

  VENDAS = 2
  COMPRAS = 4

  scope :por_cd, ->(cd) { where(cd: cd).order(:nome) }

end

app/controllers/categorias_controller.rb
# coding: UTF-8
class CategoriasController < ApplicationController
  before_action :set_categoria, only: [:show, :edit, :update, :destroy]

  def index
    @search = Categoria.search(params[:q])
    @categorias = @search.result.order(:nome)
  end

  def show
  end

  def new
    @categoria = Categoria.new
  end

  def edit
  end

  def create
    @categoria = Categoria.new(categoria_params)

    if @categoria.save
      redirect_to categorias_path, notice: 'Categoria criada com sucesso.'
    else
      render action: 'new'
    end
  end

  def update
    if @categoria.update(categoria_params)
      redirect_to categorias_path, notice: 'Categoria atualizada com sucesso.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @categoria.destroy
    redirect_to categorias_path, notice: 'Categoria apagada com sucesso.'
  end

  private
    def set_categoria
      @categoria = Categoria.find(params[:id])
    end

    def categoria_params
      params.require(:categoria).permit(:nome, :cd)
    end
end

app/views/categorias/_form.html.erb
<%= simple_form_for(@categoria) do |f| %>

  <div class="row">
    <div class="col-md-6">
      <%= f.input :nome, label: 'Nome' %>
      <%= f.input :cd, label: false, as: :boolean, checked_value: 'C', unchecked_value: 'D' %>
    </div>
  </div>

  <div class="bottom-actions">
    <%= f.button :submit, 'Salvar Categoria', class: 'btn btn-primary' %>

    <%= link_to icon(:trash, 'Apagar esta Categoria'),
          @categoria,
          method: :delete,
          data: { confirm: 'Tem certeza?' },
          class: 'btn btn-sm text-danger pull-right' unless @categoria.new_record? %>
  </div>

<% end %>

app/views/categorias/edit.html.erb
<%= page_header "Editar Categoria" do %>

  <%= link_to icon(:chevron_left, "Voltar"), categorias_path, class: 'btn' %>

<% end %>

<%= render 'form' %>

app/views/categorias/index.html.erb
<%= page_header "Categorias" %>

<div class="row">

  <div class="col-md-8">
    <table class="table table-hover table-striped">
      <thead>
        <tr>
          <th>Nome</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% @categorias.each do |categoria| %>
          <tr>
            <td><%= link_to categoria.nome, edit_categoria_path(categoria) %></td>
            <td><%= label_cd(categoria.cd) %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <p class="index_count"><span><%= @categorias.count %></span> categorias encontradas.</p>

    <%= link_to(icon(:plus, 'Nova Categoria'), new_categoria_path, class: 'btn btn-primary') %>

  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Filtros</h3>
      </div>
      <div id="filtro_pedidos" class="panel-body">
        <%= simple_form_for @search, url: categorias_path, method: 'GET' do |f| %>
          <%= f.input :nome_cont, label: "Nome" %>

          <%= f.submit 'Filtrar', class: 'btn btn-info' %>
          <%= button_tag 'Limpar', class: 'btn btn-default clear' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categorias/new.html.erb
<%= page_header "Novo Categoria" do %>
  <%= link_to icon(:chevron_left, "Voltar"), categorias_path, class: 'btn' %>
<% end %>

<%= render 'form' %>

app/views/categorias/show.html.erb
<%= page_header "Exibir Categoria" do %>
  <%= link_to icon(:chevron_left, "Voltar"), categorias_path, class: 'btn' %>
  <%= link_to icon(:edit, 'Editar Categoria'), edit_categoria_path(@categoria), class: 'btn btn-sm btn-primary' %>
<% end %>

<div class="panel panel-default">
  <div class="panel-body">

    <h4 class="text-primary">
      <%= @categoria.nome %>
    </h4>

    <div class="row">

      <div class="col-md-4 col-sm-6">

        <dl class="dl-horizontal form">

          <dt>Nome</dt>
          <dd><%= @categoria.nome %></dd>

        </dl>

      </div>

    </div>

  </div>
</div>