config/routes.rb
Rails.application.routes.draw do

  resources :formas
  resources :contas
  resources :categorias

  resources :registros do
    post :duplicate, on: :member
  end
  resources :transferencias, controller: 'registros/transferencias'

  get 'financeiro/diario'
  get 'financeiro/anual'

  root 'financeiro#diario'

end

app/controllers/financeiro_controller.rb
class FinanceiroController < ApplicationController

  def diario
    @diario = Diario.new(params[:mes])
  end

  def anual
    @anual = Anual.new(params[:ano])
  end

end

app/helpers/financeiro_helper.rb
module FinanceiroHelper
end

app/views/financeiro/anual.html.erb
<%= page_header "Financeiro Anual" do %>

<% end %>

<h2 style="text-align: center">
  <%= link_to icon(:chevron_left), financeiro_anual_path(ano: @anual.calendar.last_year) %>
  <%= @anual.calendar.year %>
  <%= link_to icon(:chevron_right), financeiro_anual_path(ano: @anual.calendar.next_year) %>
</h2>

<%= line_chart @anual.saldos,
                  label: "Saldo",
                  library: {
                    plotOptions: {
                      series: {
                        dataLabels: { enabled: true }
                      }
                    }
                  }
 %>

app/views/financeiro/diario.html.erb
<%= page_header "Diário Financeiro" do %>

<%= link_to icon(:transfer, 'Transferência'), new_transferencia_path, class: 'btn btn-sm btn-info', data: { behavior: 'load-modal'} %>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<%= link_to icon(:plus, 'Incluir Receita'), new_registro_path(cd: 'C'), class: 'btn btn-sm btn-success', data: { behavior: 'load-modal'} %> &nbsp;
<%= link_to icon(:minus, 'Incluir Despesa'), new_registro_path(cd: 'D'), class: 'btn btn-sm btn-danger', data: { behavior: 'load-modal'} %>

<% end %>


<div class="well well-sm stats">
  <h2 style="text-align: center">
    <%= link_to icon(:chevron_left), financeiro_diario_path(mes: @diario.calendar.last_month) %>
    <%= @diario.calendar.month %>
    <%= link_to icon(:chevron_right), financeiro_diario_path(mes: @diario.calendar.next_month) %>
  </h2>
</div>


<% unless @diario.calendar.future? %>

  <div class="row">

  <% @diario.contas.each do |conta| %>

    <div class="col-sm-12 col-md-6">

      <div class="panel panel-info">
        <div class="panel-heading">
          <b class="panel-title"> <%= conta.nome %> </b>
        </div>
        <div class="panel-footer upper text-right">
          <small>Saldo Inicial</small> &nbsp; <%= number_to_currency conta.saldo_inicial %>
        </div>
        <table class="table table-striped">
          <tbody id="registros_conta_caixa">
            <%= render partial: 'registros/registro', collection: conta.registros.pagos %>
          </tbody>
        </table>
        <div class="panel-footer text-right">
          <small>Saldo Final</small> &nbsp; <%= number_to_currency conta.saldo %>
        </div>
      </div>

    </div>

  <% end %>

  </div>

  <div class="well well-sm">
    <%= link_to icon(:minus, 'Incluir Despesa'), new_registro_path(cd: 'D'), class: 'btn btn-sm btn-danger', data: { behavior: 'load-modal'} %> &nbsp;
    <%= link_to icon(:plus, 'Incluir Receita'), new_registro_path(cd: 'C'), class: 'btn btn-sm btn-success', data: { behavior: 'load-modal'} %> &nbsp;

    <%= link_to icon(:transfer, 'Transferência'), new_transferencia_path, class: 'btn btn-sm btn-info pull-right', data: { behavior: 'load-modal'} %>
  </div>

  <hr/>

<% end %>

<div class="row">

  <div class="col-sm-12 col-md-6">

    <div class="panel panel-danger">
      <div class="panel-heading">
        <b class="panel-title">CONTAS A PAGAR</b>
      </div>
      <table class="table table-striped">
        <tbody id="registros_conta_caixa">
          <%= render partial: 'registros/pendente', collection: @diario.a_pagar, as: :registro %>
        </tbody>
      </table>
      <div class="panel-footer text-right">
        <small>Total</small> <%= number_to_currency @diario.a_pagar_total %>
      </div>
    </div>

  </div>

  <div class="col-sm-12 col-md-6">

    <div class="panel panel-success">
      <div class="panel-heading">
        <b class="panel-title">CONTAS A RECEBER</b>
      </div>
      <table class="table table-striped">
        <tbody id="registros_conta_caixa">
          <%= render partial: 'registros/pendente', collection: @diario.a_receber, as: :registro %>
        </tbody>
      </table>
      <div class="panel-footer text-right">
        <small>Total</small> <%= number_to_currency @diario.a_receber_total %>
      </div>
    </div>

  </div>

</div>

<hr/>
<br/>
<h3>Saldo Total por Dia</h3><br/>
<%= line_chart @diario.saldos,
                label: "Saldo",
                library: {
                  plotOptions: {
                    series: {
                      dataLabels: { enabled: false },
                      negativeColor: 'red'
                    }
                  }
                }
 %>


<br/>
<div class="well well-sm stats">
  <h2 style="text-align: center">
    <%= link_to icon(:chevron_left), financeiro_diario_path(mes: @diario.calendar.last_month) %>
    <%= @diario.calendar.month %>
    <%= link_to icon(:chevron_right), financeiro_diario_path(mes: @diario.calendar.next_month) %>
  </h2>
</div>

<h3>Receitas e Despesas - Totais do Mês </h3><br/>

<div class="well stats">
  <div class="row">
    <div class="col-sm-6 col-md-3 text-muted">
      <h1> <%= number_to_currency @diario.saldo_inicial %></h1>
      <small>SALDO ANTERIOR</small>
    </div>
    <div class="col-sm-6 col-md-3 text-danger">
      <h1> <%= number_to_currency @diario.total_despesas %></h1>
      <small>TOTAL DE DESPESAS</small>
    </div>
    <div class="col-sm-6 col-md-3 text-success">
      <h1> <%= number_to_currency @diario.total_receitas %></h1>
      <small>TOTAL DE RECEITAS</small>
    </div>
    <div class="col-sm-6 col-md-3 text-info">
      <h1> <%= number_to_currency @diario.saldo_final %></h1>
      <small>SALDO FINAL</small>
    </div>
  </div>
</div>

<div class="row">

  <div class="col-sm-12 col-md-6">

    <div class="panel panel-danger">
      <div class="panel-heading">
        <b class="panel-title">DESPESAS</b>
      </div>
      <table class="table table-striped">
        <tbody>
          <% @diario.despesas.each do |cat, valor| %>
          <tr>
            <td><%= cat.nome %></td>
            <td class='text-right' ><%= number_to_currency(valor) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>

  <div class="col-sm-12 col-md-6">

    <div class="panel panel-success">
      <div class="panel-heading">
        <b class="panel-title">RECEITAS</b>
      </div>
      <table class="table table-striped">
        <tbody>
          <% @diario.receitas.each do |cat, valor| %>
          <tr>
            <td><%= cat.nome %></td>
            <td class='text-right' ><%= number_to_currency(valor) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>